name: CI
on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [win-x64, linux-x64]

    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
    
    - name: Build
      run: dotnet publish -r ${{ matrix.platform }} -c Release --no-self-contained -p:PublishDir=../publish/${{ matrix.platform }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: publish/${{ matrix.platform }}/*