name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: x64

      - name: Rename artifacts
        run: |
          mv x64/win-x64.zip aap-${{ github.ref_name }}-win-x64.zip
          mv x64/linux-x64.zip aap-${{ github.ref_name }}-linux-x64.zip

      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          draft: true
          files: |
            aap-${{ github.ref_name }}-win-x64.zip
            aap-${{ github.ref_name }}-linux-x64.zip